kind: pipeline
type: kubernetes
name: infra-tools-test
environment:
  DOCKER_USERNAME: $$docker_username
  DOCKER_PASSWORD: $$docker_password

steps:
- name: build, test, and push commit image tag
  image: docker:dind
  when:
    event:
      - tag
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 10s
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t "autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA}" .
  - docker run autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "kubectl version --client"
  - docker run autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "helm version --client"
  - docker run autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "aws --version"
  - docker push autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA}

# - name: test image
#   image: autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA}
#   commands:
#   - kubectl version --client
#   - helm version --client
#   - aws --version

- name: publish as tagged and latest
  image: docker:dind
  when:
    event:
      - tag
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} autkast/infrastructure-tools:${DRONE_TAG} && docker tag autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} autkast/infrastructure-tools:latest
  - docker image push autkast/infrastructure-tools:${DRONE_TAG} && docker image push autkast/infrastructure-tools:latest

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
