kind: pipeline
type: kubernetes
name: infra-tools-test

steps:
- name: build & test
  image: docker
  when:
    event:
    - push
  environment:
    - DOCKER_HOST=unix://drone/docker.sock
  commands:
    - sleep 10
    - docker build -t autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} .
    - docker run --rm autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "kubectl version --client"
    - docker run --rm autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "helm version --client"
    - docker run --rm autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "aws --version"
    - docker push autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA}

- name: publish
  image: docker
  when:
    event:
    - tag
  environment:
    - DOCKER_HOST=unix://drone/docker.sock
    - DOCKER_USERNAME:
      from_secret: docker_username
    - DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker build --rm -t autkast/infrastructure-tools:sha-${DRONE_TAG} .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push autkast/infrastructure-tools:sha-${DRONE_TAG}
