kind: pipeline
type: kubernetes
name: infra-tools-test

steps:
- name: publish test image
  image: plugins/docker
  when:
    event:
    - push
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: autkast/infrastructure-tools
    tags:
    - sha-${DRONE_COMMIT_SHA}
