kind: pipeline
type: kubernetes
name: infra-tools-test

steps:
- name: build, test, and push commit image tag
  image: docker:dind
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 10s
  - docker login -u $${USERNAME} -p $${PASSWORD}
  - docker build -t "$${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA}" .
  - docker run $${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "kubectl version --client"
  - docker run $${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "helm version --client"
  - docker run $${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA} sh -c "aws --version"
  - docker push $${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA}

- name: publish as tagged and latest
  image: docker:dind
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username
  when:
    event:
      - tag
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  # - docker tag $${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA} $${USERNAME}/infrastructure-tools:${DRONE_TAG}
  - docker tag $${USERNAME}/infrastructure-tools:sha-${DRONE_COMMIT_SHA} $${USERNAME}/infrastructure-tools:latest
  # - docker image push $${USERNAME}/infrastructure-tools:${DRONE_TAG}
  - docker image push $${USERNAME}/infrastructure-tools:latest

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
