kind: pipeline
type: kubernetes
name: infra-tools-test

steps:
- name: publish test image
  image: plugins/docker
  when:
    event:
    - push
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: autkast/infrastructure-tools
    tags:
    - sha-${DRONE_COMMIT_SHA}

- name: test image
  image: autkast/infrastructure-tools:sha-${DRONE_COMMIT_SHA}
  when:
    event:
    - push
  commands:
  - kubectl version --client
  - helm version --client
  # - helm diff --help
  - aws --version
