name: test action 
on: [push]
jobs:
  Explore-gitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello actions!"
      - run: echo ${{ secrets.DOCKER_USERNAME }}
      - run: echo $(base64 ${{ secrets.DOCKER_USERNAME }})
      
